//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySolution.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Loans = new HashSet<Loan>();
        }
    
        public int BookId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> PublisherDate { get; set; }
        public string AuthorName { get; set; }
        public Nullable<int> PageNumber { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> PublisherId { get; set; }
        public string ISBN { get; set; }
        public string LibraryCode { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    
        public virtual BookCategory BookCategory { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loan> Loans { get; set; }
    }
}
