//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySolution.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int LoanId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsReturned { get; set; }
    
        public virtual User User { get; set; }
        public virtual Book Book { get; set; }
    }
}
